# Generated by Django 4.1.4 on 2023-01-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstoqueEntrada",
            fields=[],
            options={
                "verbose_name": "estoque entrada",
                "verbose_name_plural": "estoque entrada",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("estoque.estoque",),
        ),
        migrations.CreateModel(
            name="EstoqueSaida",
            fields=[],
            options={
                "verbose_name": "estoque saída",
                "verbose_name_plural": "estoque saída",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("estoque.estoque",),
        ),
    ]
